[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gmacs"
version = "0.1.0"
description = "GPU-accelerated MACS3"
requires-python = ">=3.9"
dependencies = [
    "anndata==0.10.8",
    "cupy",
    "numpy==1.26.4",
    "episcanpy==0.4.0",
    "h5py==3.11.0",
    "harmonypy==0.0.10",
    "MACS2==2.2.9.1",
    "MACS3==3.0.1",
    "hmmlearn==0.3.0",
    "magic-impute==3.0.0",
    "matplotlib==3.8.3",
    "mudata==0.2.4",
    "muon==0.1.6",
    "natsort==8.4.0",
    "pandas==2.1.1",
    "plotly==5.23.0",
    "polars==1.6.0",
    "pyarrow==17.0.0",
    "PyGSP==0.5.1",
    "pyjaspar==3.0.0",
    "PyJWT==2.8.0",
    "PyNaCl==1.5.0",
    "pynndescent==0.5.13",
    "pyogrio==0.9.0",
    "pyparsing==3.1.1",
    "pyproj==3.6.1",
    "pysam==0.22.1",
    "scanpy==1.10.2",
    "scikit-image==0.24.0",
    "scikit-learn==1.5.1",
    "scipy==1.13.1",
    "seaborn==0.13.2",
    "snapatac2==2.7.0"
]

[tool.setuptools]
packages = ["gmacs"]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "black>=23.0",
    "isort>=5.0",
    "flake8>=6.0"
]

[tool.black]
line-length = 88
target-version = ["py39"]

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-ra -q"
